layout_spectrum: 0.02165673
typography_spectrum: 0.5220723
color:
  saturation: 0.8732183
  lightness: 0.3450506
  brandStrength: 0.8883312
  rhythmicContrast: 0.1700504
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: los-gelassen
